global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'peer-review-backend'

    scheme: https
    metrics_path: /metrics

    static_configs:
      - targets:
          - 'peer-review-backend-r75l.onrender.com'